version: '2'
services:
  words-memorization-cloud-config:
    build: ./infrastructure/words-memorization-cloud-config/
    ports:
      - "8888:8888"
  words-memorization-services-registry:
    build: ./infrastructure/words-memorization-services-registry/
    ports:
      - "8761:8761"
  users-service:
    build: ./services/users-service/
  words-service:
    build: ./services/words-service/
  words-management-facade:
    build: ./facades/words-management-facade/
    ports:
      - "44050:44050"