FROM openjdk:8-jdk-alpine

COPY ["target/words-memorization-services-registry-1.0-SNAPSHOT.jar", "/app/words-memorization-services-registry.jar"]
CMD java -jar ./app/words-memorization-services-registry.jar